---
title: "Quiz 2"
subtitle: "Weeks 1 and 2: Git and GitHub, GitHub Actions, Quarto, ggplot2, tinytable, data, and the Donaldson paper"
author: "Rohan Alexander"
date: "2026-09-25"
date-format: "D MMMM, YYYY"
bibliography: references.bib
format:
  pdf:
    fontsize: 10pt
    geometry:
      - margin=2.2cm
    include-in-header:
      text: |
        \usepackage{needspace}
---

# Answer sheet

```{=latex}
\noindent Name: \rule{6.5cm}{0.4pt}\hfill Student number: \rule{4.5cm}{0.4pt}
```

\vspace{0.4cm}

Section B track (tick one): \hspace{0.5em} \framebox[1.2em][c]{\rule{0pt}{0.9em}} Python \hspace{1.5em} \framebox[1.2em][c]{\rule{0pt}{0.9em}} R

\vspace{0.3cm}

Fill in one box completely for each question. Questions 1 to 45 are for everyone. For questions 46 to 60 answer either the Python version (46P to 60P) or the R version (46R to 60R), not both, and use rows 46 to 60 below. Only this sheet is marked for the multiple-choice questions.

\vspace{0.4cm}

```{=latex}
{\setlength{\fboxsep}{0pt}\setlength{\tabcolsep}{0.9em}
\begin{center}
\begin{tabular}{llll}
\makebox[1.7em][r]{\small\textbf{1}}\hspace{0.5em}\framebox[1.55em][c]{\rule[-0.35em]{0pt}{1.35em}\scriptsize\textcolor{black!45}{A}}\hspace{0.25em}\framebox[1.55em][c]{\rule[-0.35em]{0pt}{1.35em}\scriptsize\textcolor{black!45}{B}}\hspace{0.25em}\framebox[1.55em][c]{\rule[-0.35em]{0pt}{1.35em}\scriptsize\textcolor{black!45}{C}}\hspace{0.25em}\framebox[1.55em][c]{\rule[-0.35em]{0pt}{1.35em}\scriptsize\textcolor{black!45}{D}} & \makebox[1.7em][r]{\small\textbf{16}}\hspace{0.5em}\framebox[1.55em][c]{\rule[-0.35em]{0pt}{1.35em}\scriptsize\textcolor{black!45}{A}}\hspace{0.25em}\framebox[1.55em][c]{\rule[-0.35em]{0pt}{1.35em}\scriptsize\textcolor{black!45}{B}}\hspace{0.25em}\framebox[1.55em][c]{\rule[-0.35em]{0pt}{1.35em}\scriptsize\textcolor{black!45}{C}}\hspace{0.25em}\framebox[1.55em][c]{\rule[-0.35em]{0pt}{1.35em}\scriptsize\textcolor{black!45}{D}} & \makebox[1.7em][r]{\small\textbf{31}}\hspace{0.5em}\framebox[1.55em][c]{\rule[-0.35em]{0pt}{1.35em}\scriptsize\textcolor{black!45}{A}}\hspace{0.25em}\framebox[1.55em][c]{\rule[-0.35em]{0pt}{1.35em}\scriptsize\textcolor{black!45}{B}}\hspace{0.25em}\framebox[1.55em][c]{\rule[-0.35em]{0pt}{1.35em}\scriptsize\textcolor{black!45}{C}}\hspace{0.25em}\framebox[1.55em][c]{\rule[-0.35em]{0pt}{1.35em}\scriptsize\textcolor{black!45}{D}} & \makebox[1.7em][r]{\small\textbf{46}}\hspace{0.5em}\framebox[1.55em][c]{\rule[-0.35em]{0pt}{1.35em}\scriptsize\textcolor{black!45}{A}}\hspace{0.25em}\framebox[1.55em][c]{\rule[-0.35em]{0pt}{1.35em}\scriptsize\textcolor{black!45}{B}}\hspace{0.25em}\framebox[1.55em][c]{\rule[-0.35em]{0pt}{1.35em}\scriptsize\textcolor{black!45}{C}}\hspace{0.25em}\framebox[1.55em][c]{\rule[-0.35em]{0pt}{1.35em}\scriptsize\textcolor{black!45}{D}} \\[0.55em]
\makebox[1.7em][r]{\small\textbf{2}}\hspace{0.5em}\framebox[1.55em][c]{\rule[-0.35em]{0pt}{1.35em}\scriptsize\textcolor{black!45}{A}}\hspace{0.25em}\framebox[1.55em][c]{\rule[-0.35em]{0pt}{1.35em}\scriptsize\textcolor{black!45}{B}}\hspace{0.25em}\framebox[1.55em][c]{\rule[-0.35em]{0pt}{1.35em}\scriptsize\textcolor{black!45}{C}}\hspace{0.25em}\framebox[1.55em][c]{\rule[-0.35em]{0pt}{1.35em}\scriptsize\textcolor{black!45}{D}} & \makebox[1.7em][r]{\small\textbf{17}}\hspace{0.5em}\framebox[1.55em][c]{\rule[-0.35em]{0pt}{1.35em}\scriptsize\textcolor{black!45}{A}}\hspace{0.25em}\framebox[1.55em][c]{\rule[-0.35em]{0pt}{1.35em}\scriptsize\textcolor{black!45}{B}}\hspace{0.25em}\framebox[1.55em][c]{\rule[-0.35em]{0pt}{1.35em}\scriptsize\textcolor{black!45}{C}}\hspace{0.25em}\framebox[1.55em][c]{\rule[-0.35em]{0pt}{1.35em}\scriptsize\textcolor{black!45}{D}} & \makebox[1.7em][r]{\small\textbf{32}}\hspace{0.5em}\framebox[1.55em][c]{\rule[-0.35em]{0pt}{1.35em}\scriptsize\textcolor{black!45}{A}}\hspace{0.25em}\framebox[1.55em][c]{\rule[-0.35em]{0pt}{1.35em}\scriptsize\textcolor{black!45}{B}}\hspace{0.25em}\framebox[1.55em][c]{\rule[-0.35em]{0pt}{1.35em}\scriptsize\textcolor{black!45}{C}}\hspace{0.25em}\framebox[1.55em][c]{\rule[-0.35em]{0pt}{1.35em}\scriptsize\textcolor{black!45}{D}} & \makebox[1.7em][r]{\small\textbf{47}}\hspace{0.5em}\framebox[1.55em][c]{\rule[-0.35em]{0pt}{1.35em}\scriptsize\textcolor{black!45}{A}}\hspace{0.25em}\framebox[1.55em][c]{\rule[-0.35em]{0pt}{1.35em}\scriptsize\textcolor{black!45}{B}}\hspace{0.25em}\framebox[1.55em][c]{\rule[-0.35em]{0pt}{1.35em}\scriptsize\textcolor{black!45}{C}}\hspace{0.25em}\framebox[1.55em][c]{\rule[-0.35em]{0pt}{1.35em}\scriptsize\textcolor{black!45}{D}} \\[0.55em]
\makebox[1.7em][r]{\small\textbf{3}}\hspace{0.5em}\framebox[1.55em][c]{\rule[-0.35em]{0pt}{1.35em}\scriptsize\textcolor{black!45}{A}}\hspace{0.25em}\framebox[1.55em][c]{\rule[-0.35em]{0pt}{1.35em}\scriptsize\textcolor{black!45}{B}}\hspace{0.25em}\framebox[1.55em][c]{\rule[-0.35em]{0pt}{1.35em}\scriptsize\textcolor{black!45}{C}}\hspace{0.25em}\framebox[1.55em][c]{\rule[-0.35em]{0pt}{1.35em}\scriptsize\textcolor{black!45}{D}} & \makebox[1.7em][r]{\small\textbf{18}}\hspace{0.5em}\framebox[1.55em][c]{\rule[-0.35em]{0pt}{1.35em}\scriptsize\textcolor{black!45}{A}}\hspace{0.25em}\framebox[1.55em][c]{\rule[-0.35em]{0pt}{1.35em}\scriptsize\textcolor{black!45}{B}}\hspace{0.25em}\framebox[1.55em][c]{\rule[-0.35em]{0pt}{1.35em}\scriptsize\textcolor{black!45}{C}}\hspace{0.25em}\framebox[1.55em][c]{\rule[-0.35em]{0pt}{1.35em}\scriptsize\textcolor{black!45}{D}} & \makebox[1.7em][r]{\small\textbf{33}}\hspace{0.5em}\framebox[1.55em][c]{\rule[-0.35em]{0pt}{1.35em}\scriptsize\textcolor{black!45}{A}}\hspace{0.25em}\framebox[1.55em][c]{\rule[-0.35em]{0pt}{1.35em}\scriptsize\textcolor{black!45}{B}}\hspace{0.25em}\framebox[1.55em][c]{\rule[-0.35em]{0pt}{1.35em}\scriptsize\textcolor{black!45}{C}}\hspace{0.25em}\framebox[1.55em][c]{\rule[-0.35em]{0pt}{1.35em}\scriptsize\textcolor{black!45}{D}} & \makebox[1.7em][r]{\small\textbf{48}}\hspace{0.5em}\framebox[1.55em][c]{\rule[-0.35em]{0pt}{1.35em}\scriptsize\textcolor{black!45}{A}}\hspace{0.25em}\framebox[1.55em][c]{\rule[-0.35em]{0pt}{1.35em}\scriptsize\textcolor{black!45}{B}}\hspace{0.25em}\framebox[1.55em][c]{\rule[-0.35em]{0pt}{1.35em}\scriptsize\textcolor{black!45}{C}}\hspace{0.25em}\framebox[1.55em][c]{\rule[-0.35em]{0pt}{1.35em}\scriptsize\textcolor{black!45}{D}} \\[0.55em]
\makebox[1.7em][r]{\small\textbf{4}}\hspace{0.5em}\framebox[1.55em][c]{\rule[-0.35em]{0pt}{1.35em}\scriptsize\textcolor{black!45}{A}}\hspace{0.25em}\framebox[1.55em][c]{\rule[-0.35em]{0pt}{1.35em}\scriptsize\textcolor{black!45}{B}}\hspace{0.25em}\framebox[1.55em][c]{\rule[-0.35em]{0pt}{1.35em}\scriptsize\textcolor{black!45}{C}}\hspace{0.25em}\framebox[1.55em][c]{\rule[-0.35em]{0pt}{1.35em}\scriptsize\textcolor{black!45}{D}} & \makebox[1.7em][r]{\small\textbf{19}}\hspace{0.5em}\framebox[1.55em][c]{\rule[-0.35em]{0pt}{1.35em}\scriptsize\textcolor{black!45}{A}}\hspace{0.25em}\framebox[1.55em][c]{\rule[-0.35em]{0pt}{1.35em}\scriptsize\textcolor{black!45}{B}}\hspace{0.25em}\framebox[1.55em][c]{\rule[-0.35em]{0pt}{1.35em}\scriptsize\textcolor{black!45}{C}}\hspace{0.25em}\framebox[1.55em][c]{\rule[-0.35em]{0pt}{1.35em}\scriptsize\textcolor{black!45}{D}} & \makebox[1.7em][r]{\small\textbf{34}}\hspace{0.5em}\framebox[1.55em][c]{\rule[-0.35em]{0pt}{1.35em}\scriptsize\textcolor{black!45}{A}}\hspace{0.25em}\framebox[1.55em][c]{\rule[-0.35em]{0pt}{1.35em}\scriptsize\textcolor{black!45}{B}}\hspace{0.25em}\framebox[1.55em][c]{\rule[-0.35em]{0pt}{1.35em}\scriptsize\textcolor{black!45}{C}}\hspace{0.25em}\framebox[1.55em][c]{\rule[-0.35em]{0pt}{1.35em}\scriptsize\textcolor{black!45}{D}} & \makebox[1.7em][r]{\small\textbf{49}}\hspace{0.5em}\framebox[1.55em][c]{\rule[-0.35em]{0pt}{1.35em}\scriptsize\textcolor{black!45}{A}}\hspace{0.25em}\framebox[1.55em][c]{\rule[-0.35em]{0pt}{1.35em}\scriptsize\textcolor{black!45}{B}}\hspace{0.25em}\framebox[1.55em][c]{\rule[-0.35em]{0pt}{1.35em}\scriptsize\textcolor{black!45}{C}}\hspace{0.25em}\framebox[1.55em][c]{\rule[-0.35em]{0pt}{1.35em}\scriptsize\textcolor{black!45}{D}} \\[0.55em]
\makebox[1.7em][r]{\small\textbf{5}}\hspace{0.5em}\framebox[1.55em][c]{\rule[-0.35em]{0pt}{1.35em}\scriptsize\textcolor{black!45}{A}}\hspace{0.25em}\framebox[1.55em][c]{\rule[-0.35em]{0pt}{1.35em}\scriptsize\textcolor{black!45}{B}}\hspace{0.25em}\framebox[1.55em][c]{\rule[-0.35em]{0pt}{1.35em}\scriptsize\textcolor{black!45}{C}}\hspace{0.25em}\framebox[1.55em][c]{\rule[-0.35em]{0pt}{1.35em}\scriptsize\textcolor{black!45}{D}} & \makebox[1.7em][r]{\small\textbf{20}}\hspace{0.5em}\framebox[1.55em][c]{\rule[-0.35em]{0pt}{1.35em}\scriptsize\textcolor{black!45}{A}}\hspace{0.25em}\framebox[1.55em][c]{\rule[-0.35em]{0pt}{1.35em}\scriptsize\textcolor{black!45}{B}}\hspace{0.25em}\framebox[1.55em][c]{\rule[-0.35em]{0pt}{1.35em}\scriptsize\textcolor{black!45}{C}}\hspace{0.25em}\framebox[1.55em][c]{\rule[-0.35em]{0pt}{1.35em}\scriptsize\textcolor{black!45}{D}} & \makebox[1.7em][r]{\small\textbf{35}}\hspace{0.5em}\framebox[1.55em][c]{\rule[-0.35em]{0pt}{1.35em}\scriptsize\textcolor{black!45}{A}}\hspace{0.25em}\framebox[1.55em][c]{\rule[-0.35em]{0pt}{1.35em}\scriptsize\textcolor{black!45}{B}}\hspace{0.25em}\framebox[1.55em][c]{\rule[-0.35em]{0pt}{1.35em}\scriptsize\textcolor{black!45}{C}}\hspace{0.25em}\framebox[1.55em][c]{\rule[-0.35em]{0pt}{1.35em}\scriptsize\textcolor{black!45}{D}} & \makebox[1.7em][r]{\small\textbf{50}}\hspace{0.5em}\framebox[1.55em][c]{\rule[-0.35em]{0pt}{1.35em}\scriptsize\textcolor{black!45}{A}}\hspace{0.25em}\framebox[1.55em][c]{\rule[-0.35em]{0pt}{1.35em}\scriptsize\textcolor{black!45}{B}}\hspace{0.25em}\framebox[1.55em][c]{\rule[-0.35em]{0pt}{1.35em}\scriptsize\textcolor{black!45}{C}}\hspace{0.25em}\framebox[1.55em][c]{\rule[-0.35em]{0pt}{1.35em}\scriptsize\textcolor{black!45}{D}} \\[0.55em]
\makebox[1.7em][r]{\small\textbf{6}}\hspace{0.5em}\framebox[1.55em][c]{\rule[-0.35em]{0pt}{1.35em}\scriptsize\textcolor{black!45}{A}}\hspace{0.25em}\framebox[1.55em][c]{\rule[-0.35em]{0pt}{1.35em}\scriptsize\textcolor{black!45}{B}}\hspace{0.25em}\framebox[1.55em][c]{\rule[-0.35em]{0pt}{1.35em}\scriptsize\textcolor{black!45}{C}}\hspace{0.25em}\framebox[1.55em][c]{\rule[-0.35em]{0pt}{1.35em}\scriptsize\textcolor{black!45}{D}} & \makebox[1.7em][r]{\small\textbf{21}}\hspace{0.5em}\framebox[1.55em][c]{\rule[-0.35em]{0pt}{1.35em}\scriptsize\textcolor{black!45}{A}}\hspace{0.25em}\framebox[1.55em][c]{\rule[-0.35em]{0pt}{1.35em}\scriptsize\textcolor{black!45}{B}}\hspace{0.25em}\framebox[1.55em][c]{\rule[-0.35em]{0pt}{1.35em}\scriptsize\textcolor{black!45}{C}}\hspace{0.25em}\framebox[1.55em][c]{\rule[-0.35em]{0pt}{1.35em}\scriptsize\textcolor{black!45}{D}} & \makebox[1.7em][r]{\small\textbf{36}}\hspace{0.5em}\framebox[1.55em][c]{\rule[-0.35em]{0pt}{1.35em}\scriptsize\textcolor{black!45}{A}}\hspace{0.25em}\framebox[1.55em][c]{\rule[-0.35em]{0pt}{1.35em}\scriptsize\textcolor{black!45}{B}}\hspace{0.25em}\framebox[1.55em][c]{\rule[-0.35em]{0pt}{1.35em}\scriptsize\textcolor{black!45}{C}}\hspace{0.25em}\framebox[1.55em][c]{\rule[-0.35em]{0pt}{1.35em}\scriptsize\textcolor{black!45}{D}} & \makebox[1.7em][r]{\small\textbf{51}}\hspace{0.5em}\framebox[1.55em][c]{\rule[-0.35em]{0pt}{1.35em}\scriptsize\textcolor{black!45}{A}}\hspace{0.25em}\framebox[1.55em][c]{\rule[-0.35em]{0pt}{1.35em}\scriptsize\textcolor{black!45}{B}}\hspace{0.25em}\framebox[1.55em][c]{\rule[-0.35em]{0pt}{1.35em}\scriptsize\textcolor{black!45}{C}}\hspace{0.25em}\framebox[1.55em][c]{\rule[-0.35em]{0pt}{1.35em}\scriptsize\textcolor{black!45}{D}} \\[0.55em]
\makebox[1.7em][r]{\small\textbf{7}}\hspace{0.5em}\framebox[1.55em][c]{\rule[-0.35em]{0pt}{1.35em}\scriptsize\textcolor{black!45}{A}}\hspace{0.25em}\framebox[1.55em][c]{\rule[-0.35em]{0pt}{1.35em}\scriptsize\textcolor{black!45}{B}}\hspace{0.25em}\framebox[1.55em][c]{\rule[-0.35em]{0pt}{1.35em}\scriptsize\textcolor{black!45}{C}}\hspace{0.25em}\framebox[1.55em][c]{\rule[-0.35em]{0pt}{1.35em}\scriptsize\textcolor{black!45}{D}} & \makebox[1.7em][r]{\small\textbf{22}}\hspace{0.5em}\framebox[1.55em][c]{\rule[-0.35em]{0pt}{1.35em}\scriptsize\textcolor{black!45}{A}}\hspace{0.25em}\framebox[1.55em][c]{\rule[-0.35em]{0pt}{1.35em}\scriptsize\textcolor{black!45}{B}}\hspace{0.25em}\framebox[1.55em][c]{\rule[-0.35em]{0pt}{1.35em}\scriptsize\textcolor{black!45}{C}}\hspace{0.25em}\framebox[1.55em][c]{\rule[-0.35em]{0pt}{1.35em}\scriptsize\textcolor{black!45}{D}} & \makebox[1.7em][r]{\small\textbf{37}}\hspace{0.5em}\framebox[1.55em][c]{\rule[-0.35em]{0pt}{1.35em}\scriptsize\textcolor{black!45}{A}}\hspace{0.25em}\framebox[1.55em][c]{\rule[-0.35em]{0pt}{1.35em}\scriptsize\textcolor{black!45}{B}}\hspace{0.25em}\framebox[1.55em][c]{\rule[-0.35em]{0pt}{1.35em}\scriptsize\textcolor{black!45}{C}}\hspace{0.25em}\framebox[1.55em][c]{\rule[-0.35em]{0pt}{1.35em}\scriptsize\textcolor{black!45}{D}} & \makebox[1.7em][r]{\small\textbf{52}}\hspace{0.5em}\framebox[1.55em][c]{\rule[-0.35em]{0pt}{1.35em}\scriptsize\textcolor{black!45}{A}}\hspace{0.25em}\framebox[1.55em][c]{\rule[-0.35em]{0pt}{1.35em}\scriptsize\textcolor{black!45}{B}}\hspace{0.25em}\framebox[1.55em][c]{\rule[-0.35em]{0pt}{1.35em}\scriptsize\textcolor{black!45}{C}}\hspace{0.25em}\framebox[1.55em][c]{\rule[-0.35em]{0pt}{1.35em}\scriptsize\textcolor{black!45}{D}} \\[0.55em]
\makebox[1.7em][r]{\small\textbf{8}}\hspace{0.5em}\framebox[1.55em][c]{\rule[-0.35em]{0pt}{1.35em}\scriptsize\textcolor{black!45}{A}}\hspace{0.25em}\framebox[1.55em][c]{\rule[-0.35em]{0pt}{1.35em}\scriptsize\textcolor{black!45}{B}}\hspace{0.25em}\framebox[1.55em][c]{\rule[-0.35em]{0pt}{1.35em}\scriptsize\textcolor{black!45}{C}}\hspace{0.25em}\framebox[1.55em][c]{\rule[-0.35em]{0pt}{1.35em}\scriptsize\textcolor{black!45}{D}} & \makebox[1.7em][r]{\small\textbf{23}}\hspace{0.5em}\framebox[1.55em][c]{\rule[-0.35em]{0pt}{1.35em}\scriptsize\textcolor{black!45}{A}}\hspace{0.25em}\framebox[1.55em][c]{\rule[-0.35em]{0pt}{1.35em}\scriptsize\textcolor{black!45}{B}}\hspace{0.25em}\framebox[1.55em][c]{\rule[-0.35em]{0pt}{1.35em}\scriptsize\textcolor{black!45}{C}}\hspace{0.25em}\framebox[1.55em][c]{\rule[-0.35em]{0pt}{1.35em}\scriptsize\textcolor{black!45}{D}} & \makebox[1.7em][r]{\small\textbf{38}}\hspace{0.5em}\framebox[1.55em][c]{\rule[-0.35em]{0pt}{1.35em}\scriptsize\textcolor{black!45}{A}}\hspace{0.25em}\framebox[1.55em][c]{\rule[-0.35em]{0pt}{1.35em}\scriptsize\textcolor{black!45}{B}}\hspace{0.25em}\framebox[1.55em][c]{\rule[-0.35em]{0pt}{1.35em}\scriptsize\textcolor{black!45}{C}}\hspace{0.25em}\framebox[1.55em][c]{\rule[-0.35em]{0pt}{1.35em}\scriptsize\textcolor{black!45}{D}} & \makebox[1.7em][r]{\small\textbf{53}}\hspace{0.5em}\framebox[1.55em][c]{\rule[-0.35em]{0pt}{1.35em}\scriptsize\textcolor{black!45}{A}}\hspace{0.25em}\framebox[1.55em][c]{\rule[-0.35em]{0pt}{1.35em}\scriptsize\textcolor{black!45}{B}}\hspace{0.25em}\framebox[1.55em][c]{\rule[-0.35em]{0pt}{1.35em}\scriptsize\textcolor{black!45}{C}}\hspace{0.25em}\framebox[1.55em][c]{\rule[-0.35em]{0pt}{1.35em}\scriptsize\textcolor{black!45}{D}} \\[0.55em]
\makebox[1.7em][r]{\small\textbf{9}}\hspace{0.5em}\framebox[1.55em][c]{\rule[-0.35em]{0pt}{1.35em}\scriptsize\textcolor{black!45}{A}}\hspace{0.25em}\framebox[1.55em][c]{\rule[-0.35em]{0pt}{1.35em}\scriptsize\textcolor{black!45}{B}}\hspace{0.25em}\framebox[1.55em][c]{\rule[-0.35em]{0pt}{1.35em}\scriptsize\textcolor{black!45}{C}}\hspace{0.25em}\framebox[1.55em][c]{\rule[-0.35em]{0pt}{1.35em}\scriptsize\textcolor{black!45}{D}} & \makebox[1.7em][r]{\small\textbf{24}}\hspace{0.5em}\framebox[1.55em][c]{\rule[-0.35em]{0pt}{1.35em}\scriptsize\textcolor{black!45}{A}}\hspace{0.25em}\framebox[1.55em][c]{\rule[-0.35em]{0pt}{1.35em}\scriptsize\textcolor{black!45}{B}}\hspace{0.25em}\framebox[1.55em][c]{\rule[-0.35em]{0pt}{1.35em}\scriptsize\textcolor{black!45}{C}}\hspace{0.25em}\framebox[1.55em][c]{\rule[-0.35em]{0pt}{1.35em}\scriptsize\textcolor{black!45}{D}} & \makebox[1.7em][r]{\small\textbf{39}}\hspace{0.5em}\framebox[1.55em][c]{\rule[-0.35em]{0pt}{1.35em}\scriptsize\textcolor{black!45}{A}}\hspace{0.25em}\framebox[1.55em][c]{\rule[-0.35em]{0pt}{1.35em}\scriptsize\textcolor{black!45}{B}}\hspace{0.25em}\framebox[1.55em][c]{\rule[-0.35em]{0pt}{1.35em}\scriptsize\textcolor{black!45}{C}}\hspace{0.25em}\framebox[1.55em][c]{\rule[-0.35em]{0pt}{1.35em}\scriptsize\textcolor{black!45}{D}} & \makebox[1.7em][r]{\small\textbf{54}}\hspace{0.5em}\framebox[1.55em][c]{\rule[-0.35em]{0pt}{1.35em}\scriptsize\textcolor{black!45}{A}}\hspace{0.25em}\framebox[1.55em][c]{\rule[-0.35em]{0pt}{1.35em}\scriptsize\textcolor{black!45}{B}}\hspace{0.25em}\framebox[1.55em][c]{\rule[-0.35em]{0pt}{1.35em}\scriptsize\textcolor{black!45}{C}}\hspace{0.25em}\framebox[1.55em][c]{\rule[-0.35em]{0pt}{1.35em}\scriptsize\textcolor{black!45}{D}} \\[0.55em]
\makebox[1.7em][r]{\small\textbf{10}}\hspace{0.5em}\framebox[1.55em][c]{\rule[-0.35em]{0pt}{1.35em}\scriptsize\textcolor{black!45}{A}}\hspace{0.25em}\framebox[1.55em][c]{\rule[-0.35em]{0pt}{1.35em}\scriptsize\textcolor{black!45}{B}}\hspace{0.25em}\framebox[1.55em][c]{\rule[-0.35em]{0pt}{1.35em}\scriptsize\textcolor{black!45}{C}}\hspace{0.25em}\framebox[1.55em][c]{\rule[-0.35em]{0pt}{1.35em}\scriptsize\textcolor{black!45}{D}} & \makebox[1.7em][r]{\small\textbf{25}}\hspace{0.5em}\framebox[1.55em][c]{\rule[-0.35em]{0pt}{1.35em}\scriptsize\textcolor{black!45}{A}}\hspace{0.25em}\framebox[1.55em][c]{\rule[-0.35em]{0pt}{1.35em}\scriptsize\textcolor{black!45}{B}}\hspace{0.25em}\framebox[1.55em][c]{\rule[-0.35em]{0pt}{1.35em}\scriptsize\textcolor{black!45}{C}}\hspace{0.25em}\framebox[1.55em][c]{\rule[-0.35em]{0pt}{1.35em}\scriptsize\textcolor{black!45}{D}} & \makebox[1.7em][r]{\small\textbf{40}}\hspace{0.5em}\framebox[1.55em][c]{\rule[-0.35em]{0pt}{1.35em}\scriptsize\textcolor{black!45}{A}}\hspace{0.25em}\framebox[1.55em][c]{\rule[-0.35em]{0pt}{1.35em}\scriptsize\textcolor{black!45}{B}}\hspace{0.25em}\framebox[1.55em][c]{\rule[-0.35em]{0pt}{1.35em}\scriptsize\textcolor{black!45}{C}}\hspace{0.25em}\framebox[1.55em][c]{\rule[-0.35em]{0pt}{1.35em}\scriptsize\textcolor{black!45}{D}} & \makebox[1.7em][r]{\small\textbf{55}}\hspace{0.5em}\framebox[1.55em][c]{\rule[-0.35em]{0pt}{1.35em}\scriptsize\textcolor{black!45}{A}}\hspace{0.25em}\framebox[1.55em][c]{\rule[-0.35em]{0pt}{1.35em}\scriptsize\textcolor{black!45}{B}}\hspace{0.25em}\framebox[1.55em][c]{\rule[-0.35em]{0pt}{1.35em}\scriptsize\textcolor{black!45}{C}}\hspace{0.25em}\framebox[1.55em][c]{\rule[-0.35em]{0pt}{1.35em}\scriptsize\textcolor{black!45}{D}} \\[0.55em]
\makebox[1.7em][r]{\small\textbf{11}}\hspace{0.5em}\framebox[1.55em][c]{\rule[-0.35em]{0pt}{1.35em}\scriptsize\textcolor{black!45}{A}}\hspace{0.25em}\framebox[1.55em][c]{\rule[-0.35em]{0pt}{1.35em}\scriptsize\textcolor{black!45}{B}}\hspace{0.25em}\framebox[1.55em][c]{\rule[-0.35em]{0pt}{1.35em}\scriptsize\textcolor{black!45}{C}}\hspace{0.25em}\framebox[1.55em][c]{\rule[-0.35em]{0pt}{1.35em}\scriptsize\textcolor{black!45}{D}} & \makebox[1.7em][r]{\small\textbf{26}}\hspace{0.5em}\framebox[1.55em][c]{\rule[-0.35em]{0pt}{1.35em}\scriptsize\textcolor{black!45}{A}}\hspace{0.25em}\framebox[1.55em][c]{\rule[-0.35em]{0pt}{1.35em}\scriptsize\textcolor{black!45}{B}}\hspace{0.25em}\framebox[1.55em][c]{\rule[-0.35em]{0pt}{1.35em}\scriptsize\textcolor{black!45}{C}}\hspace{0.25em}\framebox[1.55em][c]{\rule[-0.35em]{0pt}{1.35em}\scriptsize\textcolor{black!45}{D}} & \makebox[1.7em][r]{\small\textbf{41}}\hspace{0.5em}\framebox[1.55em][c]{\rule[-0.35em]{0pt}{1.35em}\scriptsize\textcolor{black!45}{A}}\hspace{0.25em}\framebox[1.55em][c]{\rule[-0.35em]{0pt}{1.35em}\scriptsize\textcolor{black!45}{B}}\hspace{0.25em}\framebox[1.55em][c]{\rule[-0.35em]{0pt}{1.35em}\scriptsize\textcolor{black!45}{C}}\hspace{0.25em}\framebox[1.55em][c]{\rule[-0.35em]{0pt}{1.35em}\scriptsize\textcolor{black!45}{D}} & \makebox[1.7em][r]{\small\textbf{56}}\hspace{0.5em}\framebox[1.55em][c]{\rule[-0.35em]{0pt}{1.35em}\scriptsize\textcolor{black!45}{A}}\hspace{0.25em}\framebox[1.55em][c]{\rule[-0.35em]{0pt}{1.35em}\scriptsize\textcolor{black!45}{B}}\hspace{0.25em}\framebox[1.55em][c]{\rule[-0.35em]{0pt}{1.35em}\scriptsize\textcolor{black!45}{C}}\hspace{0.25em}\framebox[1.55em][c]{\rule[-0.35em]{0pt}{1.35em}\scriptsize\textcolor{black!45}{D}} \\[0.55em]
\makebox[1.7em][r]{\small\textbf{12}}\hspace{0.5em}\framebox[1.55em][c]{\rule[-0.35em]{0pt}{1.35em}\scriptsize\textcolor{black!45}{A}}\hspace{0.25em}\framebox[1.55em][c]{\rule[-0.35em]{0pt}{1.35em}\scriptsize\textcolor{black!45}{B}}\hspace{0.25em}\framebox[1.55em][c]{\rule[-0.35em]{0pt}{1.35em}\scriptsize\textcolor{black!45}{C}}\hspace{0.25em}\framebox[1.55em][c]{\rule[-0.35em]{0pt}{1.35em}\scriptsize\textcolor{black!45}{D}} & \makebox[1.7em][r]{\small\textbf{27}}\hspace{0.5em}\framebox[1.55em][c]{\rule[-0.35em]{0pt}{1.35em}\scriptsize\textcolor{black!45}{A}}\hspace{0.25em}\framebox[1.55em][c]{\rule[-0.35em]{0pt}{1.35em}\scriptsize\textcolor{black!45}{B}}\hspace{0.25em}\framebox[1.55em][c]{\rule[-0.35em]{0pt}{1.35em}\scriptsize\textcolor{black!45}{C}}\hspace{0.25em}\framebox[1.55em][c]{\rule[-0.35em]{0pt}{1.35em}\scriptsize\textcolor{black!45}{D}} & \makebox[1.7em][r]{\small\textbf{42}}\hspace{0.5em}\framebox[1.55em][c]{\rule[-0.35em]{0pt}{1.35em}\scriptsize\textcolor{black!45}{A}}\hspace{0.25em}\framebox[1.55em][c]{\rule[-0.35em]{0pt}{1.35em}\scriptsize\textcolor{black!45}{B}}\hspace{0.25em}\framebox[1.55em][c]{\rule[-0.35em]{0pt}{1.35em}\scriptsize\textcolor{black!45}{C}}\hspace{0.25em}\framebox[1.55em][c]{\rule[-0.35em]{0pt}{1.35em}\scriptsize\textcolor{black!45}{D}} & \makebox[1.7em][r]{\small\textbf{57}}\hspace{0.5em}\framebox[1.55em][c]{\rule[-0.35em]{0pt}{1.35em}\scriptsize\textcolor{black!45}{A}}\hspace{0.25em}\framebox[1.55em][c]{\rule[-0.35em]{0pt}{1.35em}\scriptsize\textcolor{black!45}{B}}\hspace{0.25em}\framebox[1.55em][c]{\rule[-0.35em]{0pt}{1.35em}\scriptsize\textcolor{black!45}{C}}\hspace{0.25em}\framebox[1.55em][c]{\rule[-0.35em]{0pt}{1.35em}\scriptsize\textcolor{black!45}{D}} \\[0.55em]
\makebox[1.7em][r]{\small\textbf{13}}\hspace{0.5em}\framebox[1.55em][c]{\rule[-0.35em]{0pt}{1.35em}\scriptsize\textcolor{black!45}{A}}\hspace{0.25em}\framebox[1.55em][c]{\rule[-0.35em]{0pt}{1.35em}\scriptsize\textcolor{black!45}{B}}\hspace{0.25em}\framebox[1.55em][c]{\rule[-0.35em]{0pt}{1.35em}\scriptsize\textcolor{black!45}{C}}\hspace{0.25em}\framebox[1.55em][c]{\rule[-0.35em]{0pt}{1.35em}\scriptsize\textcolor{black!45}{D}} & \makebox[1.7em][r]{\small\textbf{28}}\hspace{0.5em}\framebox[1.55em][c]{\rule[-0.35em]{0pt}{1.35em}\scriptsize\textcolor{black!45}{A}}\hspace{0.25em}\framebox[1.55em][c]{\rule[-0.35em]{0pt}{1.35em}\scriptsize\textcolor{black!45}{B}}\hspace{0.25em}\framebox[1.55em][c]{\rule[-0.35em]{0pt}{1.35em}\scriptsize\textcolor{black!45}{C}}\hspace{0.25em}\framebox[1.55em][c]{\rule[-0.35em]{0pt}{1.35em}\scriptsize\textcolor{black!45}{D}} & \makebox[1.7em][r]{\small\textbf{43}}\hspace{0.5em}\framebox[1.55em][c]{\rule[-0.35em]{0pt}{1.35em}\scriptsize\textcolor{black!45}{A}}\hspace{0.25em}\framebox[1.55em][c]{\rule[-0.35em]{0pt}{1.35em}\scriptsize\textcolor{black!45}{B}}\hspace{0.25em}\framebox[1.55em][c]{\rule[-0.35em]{0pt}{1.35em}\scriptsize\textcolor{black!45}{C}}\hspace{0.25em}\framebox[1.55em][c]{\rule[-0.35em]{0pt}{1.35em}\scriptsize\textcolor{black!45}{D}} & \makebox[1.7em][r]{\small\textbf{58}}\hspace{0.5em}\framebox[1.55em][c]{\rule[-0.35em]{0pt}{1.35em}\scriptsize\textcolor{black!45}{A}}\hspace{0.25em}\framebox[1.55em][c]{\rule[-0.35em]{0pt}{1.35em}\scriptsize\textcolor{black!45}{B}}\hspace{0.25em}\framebox[1.55em][c]{\rule[-0.35em]{0pt}{1.35em}\scriptsize\textcolor{black!45}{C}}\hspace{0.25em}\framebox[1.55em][c]{\rule[-0.35em]{0pt}{1.35em}\scriptsize\textcolor{black!45}{D}} \\[0.55em]
\makebox[1.7em][r]{\small\textbf{14}}\hspace{0.5em}\framebox[1.55em][c]{\rule[-0.35em]{0pt}{1.35em}\scriptsize\textcolor{black!45}{A}}\hspace{0.25em}\framebox[1.55em][c]{\rule[-0.35em]{0pt}{1.35em}\scriptsize\textcolor{black!45}{B}}\hspace{0.25em}\framebox[1.55em][c]{\rule[-0.35em]{0pt}{1.35em}\scriptsize\textcolor{black!45}{C}}\hspace{0.25em}\framebox[1.55em][c]{\rule[-0.35em]{0pt}{1.35em}\scriptsize\textcolor{black!45}{D}} & \makebox[1.7em][r]{\small\textbf{29}}\hspace{0.5em}\framebox[1.55em][c]{\rule[-0.35em]{0pt}{1.35em}\scriptsize\textcolor{black!45}{A}}\hspace{0.25em}\framebox[1.55em][c]{\rule[-0.35em]{0pt}{1.35em}\scriptsize\textcolor{black!45}{B}}\hspace{0.25em}\framebox[1.55em][c]{\rule[-0.35em]{0pt}{1.35em}\scriptsize\textcolor{black!45}{C}}\hspace{0.25em}\framebox[1.55em][c]{\rule[-0.35em]{0pt}{1.35em}\scriptsize\textcolor{black!45}{D}} & \makebox[1.7em][r]{\small\textbf{44}}\hspace{0.5em}\framebox[1.55em][c]{\rule[-0.35em]{0pt}{1.35em}\scriptsize\textcolor{black!45}{A}}\hspace{0.25em}\framebox[1.55em][c]{\rule[-0.35em]{0pt}{1.35em}\scriptsize\textcolor{black!45}{B}}\hspace{0.25em}\framebox[1.55em][c]{\rule[-0.35em]{0pt}{1.35em}\scriptsize\textcolor{black!45}{C}}\hspace{0.25em}\framebox[1.55em][c]{\rule[-0.35em]{0pt}{1.35em}\scriptsize\textcolor{black!45}{D}} & \makebox[1.7em][r]{\small\textbf{59}}\hspace{0.5em}\framebox[1.55em][c]{\rule[-0.35em]{0pt}{1.35em}\scriptsize\textcolor{black!45}{A}}\hspace{0.25em}\framebox[1.55em][c]{\rule[-0.35em]{0pt}{1.35em}\scriptsize\textcolor{black!45}{B}}\hspace{0.25em}\framebox[1.55em][c]{\rule[-0.35em]{0pt}{1.35em}\scriptsize\textcolor{black!45}{C}}\hspace{0.25em}\framebox[1.55em][c]{\rule[-0.35em]{0pt}{1.35em}\scriptsize\textcolor{black!45}{D}} \\[0.55em]
\makebox[1.7em][r]{\small\textbf{15}}\hspace{0.5em}\framebox[1.55em][c]{\rule[-0.35em]{0pt}{1.35em}\scriptsize\textcolor{black!45}{A}}\hspace{0.25em}\framebox[1.55em][c]{\rule[-0.35em]{0pt}{1.35em}\scriptsize\textcolor{black!45}{B}}\hspace{0.25em}\framebox[1.55em][c]{\rule[-0.35em]{0pt}{1.35em}\scriptsize\textcolor{black!45}{C}}\hspace{0.25em}\framebox[1.55em][c]{\rule[-0.35em]{0pt}{1.35em}\scriptsize\textcolor{black!45}{D}} & \makebox[1.7em][r]{\small\textbf{30}}\hspace{0.5em}\framebox[1.55em][c]{\rule[-0.35em]{0pt}{1.35em}\scriptsize\textcolor{black!45}{A}}\hspace{0.25em}\framebox[1.55em][c]{\rule[-0.35em]{0pt}{1.35em}\scriptsize\textcolor{black!45}{B}}\hspace{0.25em}\framebox[1.55em][c]{\rule[-0.35em]{0pt}{1.35em}\scriptsize\textcolor{black!45}{C}}\hspace{0.25em}\framebox[1.55em][c]{\rule[-0.35em]{0pt}{1.35em}\scriptsize\textcolor{black!45}{D}} & \makebox[1.7em][r]{\small\textbf{45}}\hspace{0.5em}\framebox[1.55em][c]{\rule[-0.35em]{0pt}{1.35em}\scriptsize\textcolor{black!45}{A}}\hspace{0.25em}\framebox[1.55em][c]{\rule[-0.35em]{0pt}{1.35em}\scriptsize\textcolor{black!45}{B}}\hspace{0.25em}\framebox[1.55em][c]{\rule[-0.35em]{0pt}{1.35em}\scriptsize\textcolor{black!45}{C}}\hspace{0.25em}\framebox[1.55em][c]{\rule[-0.35em]{0pt}{1.35em}\scriptsize\textcolor{black!45}{D}} & \makebox[1.7em][r]{\small\textbf{60}}\hspace{0.5em}\framebox[1.55em][c]{\rule[-0.35em]{0pt}{1.35em}\scriptsize\textcolor{black!45}{A}}\hspace{0.25em}\framebox[1.55em][c]{\rule[-0.35em]{0pt}{1.35em}\scriptsize\textcolor{black!45}{B}}\hspace{0.25em}\framebox[1.55em][c]{\rule[-0.35em]{0pt}{1.35em}\scriptsize\textcolor{black!45}{C}}\hspace{0.25em}\framebox[1.55em][c]{\rule[-0.35em]{0pt}{1.35em}\scriptsize\textcolor{black!45}{D}} \\[0.55em]
\end{tabular}
\end{center}}
```

\newpage

# Section A: everyone (questions 1 to 45)

These questions are about Git and GitHub, GitHub Actions, Quarto [@quarto], ggplot2 [@ggplot2], tinytable [@tinytable], working with data, and the Donaldson paper in @Alexander2023.

\needspace{7\baselineskip}
**1.** Which statement is correct?

(A) Git and GitHub are two names for the same thing; the software was renamed when Microsoft bought it
(B) Git is version control software on your laptop; GitHub is a website that hosts Git repositories
(C) Git only works while you are connected to GitHub, because the history is stored on the website
(D) GitHub is the software on your laptop; Git is the website where the repositories are hosted

\needspace{7\baselineskip}
**2.** You changed `paper.qmd` and `notes.txt`, but only want the changes to `paper.qmd` in the next snapshot. What do you run first?

(A) `git push`
(B) `git commit -m "Update paper"`
(C) `git add .`
(D) `git add paper.qmd`

\needspace{7\baselineskip}
**3.** In which order do you run these to get your local changes onto GitHub?

(A) push, add, commit
(B) commit, add, push
(C) add, commit, push
(D) add, push, commit

\needspace{7\baselineskip}
**4.** Which commit message will be most useful to you in three weeks?

(A) "Update graph, fix typos, add data, rewrite intro, change references"
(B) "Fixed the problem from yesterday"
(C) "Add histogram of occupancy rate to data section"
(D) "Made some more changes to paper.qmd"

\needspace{7\baselineskip}
**5.** What does the Donaldson paper rubric ask for with respect to commits?

(A) A commit every time a file is saved
(B) At least a handful of commits, with meaningful messages
(C) One commit when the paper is finished, so that the history is clean
(D) Commit messages that begin with the date

\needspace{7\baselineskip}
**6.** `git push` fails because "the remote contains work that you do not have locally". What should you do next?

(A) `git pull`, deal with any conflicts, then push again
(B) `git push --force`, so that your version wins
(C) Delete your local copy, clone again, and redo your changes by hand
(D) Make a new branch and push that instead, leaving `main` as it is

\needspace{7\baselineskip}
**7.** After a pull you find `<<<<<<< HEAD`, `=======`, and `>>>>>>>` inside `paper.qmd`. What has happened, and what do you do?

(A) The file was damaged during the pull; discard it with `git checkout paper.qmd`, and then pull again
(B) Two edits to the same lines could not be merged; keep what you want, delete the markers, then add and commit
(C) Git has already kept the newer of the two versions; delete the markers and commit the file as it is
(D) The pull is only half finished; run `git pull` again and the markers will be removed for you

\needspace{7\baselineskip}
**8.** What is a pull request for?

(A) To propose changes from a branch or fork, so they can be reviewed before they are merged
(B) To make a private backup of your branch on GitHub, which only you are able to see
(C) To report a problem or ask a question about a repository, so the owner can respond
(D) To download the latest version of a repository; it is GitHub's name for `git pull`

\needspace{7\baselineskip}
**9.** You want to add your group's slides to the class repo, which you do not own. What is the usual route?

(A) Download the repo as a zip, add the slides, and upload it as a new repo of your own
(B) Clone the class repo, add the slides, and push to `main`
(C) Fork the repo, make the change in your fork, then open a pull request
(D) Open an issue on the class repo and attach the slides

\needspace{7\baselineskip}
**10.** Which of these belongs in `.gitignore`?

(A) `references.bib`
(B) `README.md`
(C) `data/analysis_data.parquet`, which the paper reads
(D) `.env`, containing your API key

\needspace{7\baselineskip}
**11.** Where does a GitHub Actions workflow run?

(A) On a fresh computer that GitHub provides, when a trigger you specified happens
(B) On your laptop, whenever you push
(C) On your laptop, but only if it is switched on at the scheduled time
(D) On a computer that GitHub provides, using the Python and packages installed on your laptop

\needspace{7\baselineskip}
**12.** A workflow has `cron: '0 7 * * *'`. When does it run?

(A) Every day at 7:00 UTC
(B) Every day at 7:00 Toronto time
(C) Every 7 minutes
(D) On the 7th day of each month

\needspace{7\baselineskip}
**13.** The Bluesky example needs a password. Where should the password live?

(A) In the workflow YAML file, since only people with write access are able to edit that
(B) In the script itself, since the repo is private and only collaborators can read the code
(C) In a `.env` file that is committed to the repo, so that the workflow is able to load it
(D) As a repository secret in GitHub's settings, passed to the script as an environment variable

\needspace{7\baselineskip}
**14.** Your scheduled workflow ran and the script succeeded, but no new data file appeared in the repo. What is the most likely cause?

(A) Workflow permissions are read-only, so the workflow could not commit the file back
(B) The file was saved to your laptop, because that is where the script was written
(C) The cron expression is in UTC, so the file will only appear on the following day
(D) Scheduled workflows can read data, but they are not allowed to create new files

\needspace{7\baselineskip}
**15.** A `.qmd` file has three kinds of content. Which three?

(A) A title, R code, and the rendered PDF
(B) An R script, a Python script, and a Markdown file
(C) A YAML header, Markdown prose, and code chunks
(D) A YAML header, LaTeX, and BibTeX

\needspace{7\baselineskip}
**16.** Your paper renders to PDF. You now want the same content as a web page. What do you change?

(A) Rename `paper.pdf` to `paper.html`
(B) The `format` line in the YAML header, from `pdf` to `html`
(C) Make a second `.qmd` with the same content and `format: html`
(D) Rewrite each code chunk so that it produces HTML

\needspace{7\baselineskip}
**17.** The Donaldson checklist says "No R code or raw output in final PDF". Which chunk options do that for a chunk that makes a graph, while keeping the graph?

(A) `#| output: false`, `#| warning: false`, `#| message: false`
(B) `#| include: false`, `#| warning: false`, `#| message: false`
(C) `#| echo: false`, `#| warning: false`, `#| message: false`
(D) `#| eval: false`, `#| warning: false`, `#| message: false`

\needspace{7\baselineskip}
**18.** What does the chunk option `#| eval: false` do?

(A) The code is shown, but it is not run
(B) Neither the code nor its output is shown
(C) The code is run once, and the result is cached
(D) The code is run but not shown

\needspace{7\baselineskip}
**19.** You want to write "as shown in Figure 2" and have the number update by itself if figures move. What do you need?

(A) `#| label: occupancy` on the chunk, and `@occupancy` in the text
(B) `#| label: fig-occupancy` on the chunk, and `@fig-occupancy` in the text
(C) `#| label: fig-occupancy` on the chunk, and `#fig-occupancy` in the text
(D) `#| fig-cap:` on the chunk; Quarto then matches "Figure 2" in the text

\needspace{7\baselineskip}
**20.** Where does a figure's caption come from in a Quarto paper?

(A) `labs(title = ...)` in the ggplot
(B) `labs(caption = ...)` in the ggplot
(C) The `#| label:` chunk option
(D) The `#| fig-cap:` chunk option

\needspace{7\baselineskip}
**21.** How do you cite R so that it appears in the reference list?

(A) Add a BibTeX entry to `references.bib`, which the YAML names, and write `@citeR` in the text
(B) Type "(R Core Team 2025)" in the text, and type the full reference at the end of the paper
(C) R is software rather than literature, so it is credited in the README, not the reference list
(D) Run `citation()` in a chunk, so that its output appears in the paper where R is mentioned

\needspace{7\baselineskip}
**22.** Under the Donaldson rubric, what happens if R (or Python) is not cited?

(A) Nothing happens; software does not need to be cited
(B) The paper gets 0 overall, whatever the rest of it is like
(C) The paper is returned for correction and resubmission
(D) One mark is lost from the referencing component

\needspace{7\baselineskip}
**23.** Which command renders `paper.qmd` from the terminal?

(A) `quarto render paper.qmd`
(B) `Rscript paper.qmd`
(C) `quarto run paper.qmd`
(D) `quarto compile paper.qmd`

\needspace{7\baselineskip}
**24.** In a Quarto website project, which file holds the site title, the navigation bar, and the output folder?

(A) `index.qmd`
(B) `styles.css`
(C) `docs/index.html`
(D) `_quarto.yml`

\needspace{7\baselineskip}
**25.** Why did we set `output-dir: docs` for the website?

(A) So that the rendered site is kept out of the repo and is not committed
(B) Quarto can only render a website into a folder called `docs`
(C) GitHub Pages can serve a site from the `/docs` folder of the `main` branch
(D) So that visitors to the site cannot see the `.qmd` source files

\needspace{7\baselineskip}
**26.** In `ggplot(daily, aes(x = date, y = service_users))`, what does `aes()` do?

(A) Sets fixed visual properties, such as making every point on the graph blue
(B) Filters the data down to just the variables that are named inside it
(C) Maps variables in the data to visual properties, such as position or colour
(D) Chooses the type of graph that is drawn, such as points, lines, or bars

\needspace{7\baselineskip}
**27.** You have nightly shelter occupancy for a year and want to show how it changed over time. Which geom?

(A) `geom_boxplot()`
(B) `geom_density()`
(C) `geom_histogram()`
(D) `geom_line()`

\needspace{7\baselineskip}
**28.** What is the difference between `aes(colour = sector)` and `geom_line(colour = "blue")`?

(A) Both give one colour per sector; the second just chooses which colour is used first
(B) The first only works if `sector` is numeric; the second works for any type of column
(C) The first gives one colour per sector and a legend; the second makes every line blue
(D) The second gives one colour per sector and a legend; the first makes every line the same

\needspace{7\baselineskip}
**29.** Which operator adds a layer to a ggplot?

(A) `&`
(B) `+`
(C) `%>%`
(D) `|>`

\needspace{7\baselineskip}
**30.** Which function sets the axis labels and the legend title?

(A) `ggtitle()`
(B) `labs()`
(C) `aes()`
(D) `theme()`

\needspace{7\baselineskip}
**31.** You want one small panel per sector rather than five lines on one panel. What do you add?

(A) `facet_wrap(~ sector)`
(B) `group_by(sector)` before the call to `ggplot()`
(C) `aes(group = sector)`
(D) `geom_line(sector)`

\needspace{7\baselineskip}
**32.** The Donaldson paper says "Graphs must show the actual data, or as close to it as possible, not summary statistics." You have 5,000 observations of a numeric variable in five groups. Which graph is best?

(A) A bar chart of the five group means, with error bars
(B) A table of the five group means and standard deviations
(C) A boxplot for each of the five groups, with outliers marked
(D) All 5,000 points by group, jittered and semi-transparent

\needspace{7\baselineskip}
**33.** What does `tt(latest)` do?

(A) Prints the first rows of the data frame `latest` to the console, like `head()`
(B) Runs a t-test on each pair of numeric columns in the data frame `latest`
(C) Turns the data frame `latest` into a formatted table for PDF, HTML, or Word
(D) Transposes the data frame `latest`, so that its rows become its columns

\needspace{7\baselineskip}
**34.** The rubric says tables should "have an appropriate number of decimal places and use comma separators for thousands". What handles that in tinytable?

(A) `options(digits = 2)` at the top of the document
(B) `format_tt()`, for instance with `digits` and `num_mark_big = ","`
(C) `round()` inside `mutate()`; tinytable cannot format numbers
(D) Converting the numbers to text with the commas typed in

\needspace{7\baselineskip}
**35.** How do you make a table that can be referred to as "Table 1" in the text?

(A) `#| label: tbl-latest` with `#| tbl-cap: "..."` on the chunk, then `@tbl-latest` in the text
(B) `#| tbl-cap: "..."` on the chunk, then type "Table 1" in the text
(C) `#| label: tab-latest` with `#| tbl-cap: "..."` on the chunk, then `@tab-latest` in the text
(D) `#| label: fig-latest` on the chunk, then `@fig-latest` in the text

\needspace{7\baselineskip}
**36.** Which of these is the best way to show an occupancy rate in a table for a general reader?

(A) 82.35294%
(B) 0.8235294
(C) 8.24e-01
(D) 82.4%

\needspace{7\baselineskip}
**37.** Why did we save the shelter data as Parquet rather than CSV?

(A) A CSV file cannot hold more than about a million rows, and Parquet has no limit
(B) Parquet keeps column types (a date stays a date) and the files are much smaller
(C) Parquet can be opened and checked in a text editor, which a CSV file cannot be
(D) Parquet is the only file format that both Python and R are able to read

\needspace{7\baselineskip}
**38.** What is the rule for raw data according to @Wilson2017?

(A) Fix obvious errors by hand first, then save that as the raw data
(B) Delete it once the cleaned version exists, to avoid confusion
(C) Save it as it arrived, never edit it by hand, and do all cleaning in scripts
(D) Clean it in place, so that there is only ever one version of the data

\needspace{7\baselineskip}
**39.** In the Donaldson paper, where should `paper.qmd` get its data from?

(A) From the raw data file, with all of the cleaning done in the paper's chunks
(B) From `~/Downloads`, using the full path so there is no ambiguity
(C) Directly from the Open Data Toronto server every time it renders, so the data are always current
(D) From the saved, cleaned file in the repo that your scripts produced

\needspace{7\baselineskip}
**40.** Why does the simulation script need a seed?

(A) So that each person who runs the script gets a different simulated dataset
(B) It removes the randomness, so that the simulated data match the real data
(C) So the same "random" data are generated each time, and results can be reproduced
(D) R and Python cannot generate random numbers at all unless a seed has been set

\needspace{7\baselineskip}
**41.** Why simulate the dataset before getting the real one?

(A) The simulated data are used in the paper instead, if the real data turn out to be too messy
(B) Comparing the two datasets is how missing values in the real data are found and filled in
(C) The simulated data are added to the real data, which increases the sample size for the paper
(D) It makes you decide what each variable should look like, and gives you data to test code against

\needspace{7\baselineskip}
**42.** Which is a useful test for your cleaned shelter dataset?

(A) Occupied beds is never negative or above capacity; dates fall in the expected range
(B) The cleaning script ran from start to finish without producing an error message
(C) The mean of occupied beds is equal to the mean in the simulated dataset
(D) The cleaned dataset has exactly the same number of rows as the raw dataset

\needspace{7\baselineskip}
**43.** Which date format does the Donaldson checklist ask for?

(A) 2 March 2026
(B) 03/02/2026
(C) 2/3/2026
(D) 02.03.26

\needspace{7\baselineskip}
**44.** What must the README of your Donaldson repo include?

(A) A copy of the abstract, so readers need not open the PDF
(B) A statement of whether LLMs were used and, if so, how
(C) A list of every R function that the scripts call
(D) Your student number and the course code, for marking

\needspace{7\baselineskip}
**45.** Which of these is NOT acceptable in a Donaldson submission?

(A) A link to the GitHub repo, given in a footnote on page one
(B) Graphs made with ggplot2 and tables made with tinytable
(C) An abstract of four sentences, written for a general reader
(D) A repo called "Paper 1" whose title page names the course

\newpage

# Section B: choose Python or R (questions 46 to 60)

Answer one track only, and tick it on the answer sheet. The first five questions are about setting up and running a project; the last ten ask for the code that does a task.

## Python track (uv and polars)

These questions use uv [@uv] and polars [@polars].

\needspace{7\baselineskip}
**46P.** You are starting a new analysis. What does `uv init shelter_usage` create?

(A) An environment with the common data science packages already installed
(B) A folder set up as a Python project, with a `pyproject.toml` to record its packages
(C) A new GitHub repository called `shelter_usage`, linked to a folder on your laptop
(D) A single installation of Python that all of your projects will then share

\needspace{7\baselineskip}
**47P.** You need polars for your cleaning script. Which command installs it and records it as a dependency of the project?

(A) `import polars`
(B) `uv add polars`
(C) `uv run polars`
(D) `pip install polars`

\needspace{7\baselineskip}
**48P.** What does `uv run 02-download_data.py` do?

(A) Runs the script with whatever Python and packages happen to be installed on the computer
(B) Installs the script into the project as a package, so other scripts can import it
(C) Runs the script, and then adds and commits any files that the script has produced
(D) Runs the script in the project's own environment, creating or updating it first if needed

\needspace{7\baselineskip}
**49P.** Your repo contains `pyproject.toml` and `uv.lock`. What is `uv.lock` for?

(A) It lists the packages you asked for; `pyproject.toml` records the exact versions
(B) It stops collaborators from adding or removing packages without your approval
(C) It records the exact version of every package, so others get the same environment
(D) It is a temporary file that uv recreates each run, so it belongs in `.gitignore`

\needspace{7\baselineskip}
**50P.** A collaborator clones your repo. Which single command recreates your environment on their laptop?

(A) `pip install -r requirements.txt`
(B) `uv init`
(C) `uv lock`
(D) `uv sync`

\needspace{7\baselineskip}
**51P.** Read the file `cleaned_shelter_usage.parquet` into a data frame.

(A) `df = open("cleaned_shelter_usage.parquet")`
(B) `df = pl.read_csv("cleaned_shelter_usage.parquet")`
(C) `df = pl.DataFrame("cleaned_shelter_usage.parquet")`
(D) `df = pl.read_parquet("cleaned_shelter_usage.parquet")`

\needspace{7\baselineskip}
**52P.** Keep only the columns `date` and `occupied_beds`.

(A) `df.filter(["date", "occupied_beds"])`
(B) `df.select(["date", "occupied_beds"])`
(C) `df.drop(["date", "occupied_beds"])`
(D) `df.with_columns(["date", "occupied_beds"])`

\needspace{7\baselineskip}
**53P.** Keep only the rows where `occupied_beds` is not missing.

(A) `df.drop("occupied_beds")`
(B) `df.filter(pl.col("occupied_beds") != None)`
(C) `df.filter(pl.col("occupied_beds").is_not_null())`
(D) `df.select(pl.col("occupied_beds").is_not_null())`

\needspace{7\baselineskip}
**54P.** Add a column `occupancy_rate`, equal to occupied beds divided by capacity, keeping all the other columns.

(A) `df.select((pl.col("occupied_beds") / pl.col("capacity")).alias("occupancy_rate"))`
(B) `df.with_columns((pl.col("occupied_beds") / pl.col("capacity")).alias("occupancy_rate"))`
(C) `df.with_columns(("occupied_beds" / "capacity").alias("occupancy_rate"))`
(D) `df["occupancy_rate"] = df["occupied_beds"] / df["capacity"]`

\needspace{7\baselineskip}
**55P.** Get the total number of occupied beds on each date.

(A) `df.group_by("date").agg(pl.col("occupied_beds").count())`
(B) `df.group_by("date").agg(pl.col("occupied_beds").sum())`
(C) `df.group_by("occupied_beds").agg(pl.col("date").sum())`
(D) `df.select(pl.col("occupied_beds").sum())`

\needspace{7\baselineskip}
**56P.** Rename the column `OCCUPANCY_DATE` to `date`.

(A) `df.rename({"date": "OCCUPANCY_DATE"})`
(B) `df.select("date")`
(C) `df.with_columns(pl.col("OCCUPANCY_DATE").alias("date"))`
(D) `df.rename({"OCCUPANCY_DATE": "date"})`

\needspace{7\baselineskip}
**57P.** Make a simulation give the same result every time it is run.

(A) `rng = np.random.normal(seed=853)`
(B) `rng = np.random.default_rng()`
(C) `rng = np.random.default_rng(seed=None)`
(D) `rng = np.random.default_rng(seed=853)`

\needspace{7\baselineskip}
**58P.** Find out how many rows and how many columns the data frame has.

(A) `df.shape`
(B) `len(df)`
(C) `df.columns`
(D) `df.describe()`

\needspace{7\baselineskip}
**59P.** The `date` column was read in as text. Why convert it to a date type (for instance with `pl.col("date").str.strptime(pl.Date, "%Y-%m-%d")`) before graphing over time?

(A) So the axis is ordered and spaced as time, not as alphabetical labels
(B) It makes no difference to the graph; it is only tidier to store dates as dates
(C) ggplot2 cannot put a text column on an axis at all, and gives an error
(D) Parquet cannot store a text column, so the file could not otherwise be saved

\needspace{7\baselineskip}
**60P.** Save the cleaned data frame, as Parquet, for the paper to read.

(A) `pl.save(df, "cleaned.parquet")`
(B) `df.write_csv("cleaned.parquet")`
(C) `df.write_parquet("cleaned.parquet")`
(D) `df.to_parquet("cleaned.parquet")`

\newpage

## R track (RStudio Projects, dplyr, and arrow)

These questions use R [@citeR], dplyr [@dplyr], and arrow [@arrow].

\needspace{7\baselineskip}
**46R.** You open your work as an RStudio Project (`shelter_usage.Rproj`). What does that give you?

(A) A package library with the common data science packages already installed
(B) The working directory is the project folder, so relative paths work on any computer
(C) A new GitHub repository called `shelter_usage`, linked to a folder on your laptop
(D) A single installation of R that all of your projects will then share

\needspace{7\baselineskip}
**47R.** You need tinytable for your tables, and have never used it on this computer. Which command installs it?

(A) `update.packages("tinytable")`
(B) `install.packages("tinytable")`
(C) `require("tinytable")`
(D) `library(tinytable)`

\needspace{7\baselineskip}
**48R.** Before committing, you restart R and run `02-download_data.R` from top to bottom. Why?

(A) Restarting R updates your packages, so the script is checked against the newest versions
(B) A script only saves its output properly when it is run from a fresh session
(C) It clears the saved data files, so that the download starts again from nothing
(D) To check the script works on its own, not relying on objects left in your environment

\needspace{7\baselineskip}
**49R.** The Donaldson rubric says to avoid `setwd("/Users/rohan/Documents/paper")` and hard-coded paths. Why?

(A) Reading from an absolute path is much slower than reading from a relative path
(B) `setwd()` is deprecated, and it no longer works in current versions of R and RStudio
(C) That path exists only on your computer, so the script fails for everyone else
(D) `setwd()` changes the working directory permanently, for all of your projects

\needspace{7\baselineskip}
**50R.** Which pipe does the Donaldson rubric ask you to use in R?

(A) The assignment arrow, `->`
(B) The magrittr pipe, `%>%`
(C) The plus sign, `+`
(D) The base pipe, `|>`

\needspace{7\baselineskip}
**51R.** Read the file `cleaned_shelter_usage.parquet` into a data frame.

(A) `df <- load("cleaned_shelter_usage.parquet")`
(B) `df <- read_csv("cleaned_shelter_usage.parquet")`
(C) `df <- data.frame("cleaned_shelter_usage.parquet")`
(D) `df <- read_parquet("cleaned_shelter_usage.parquet")`

\needspace{7\baselineskip}
**52R.** Keep only the columns `date` and `occupied_beds`.

(A) `df |> filter(date, occupied_beds)`
(B) `df |> select(date, occupied_beds)`
(C) `df |> select(-date, -occupied_beds)`
(D) `df |> mutate(date, occupied_beds)`

\needspace{7\baselineskip}
**53R.** Keep only the rows where `occupied_beds` is not missing.

(A) `df |> select(-occupied_beds)`
(B) `df |> filter(occupied_beds != NA)`
(C) `df |> filter(!is.na(occupied_beds))`
(D) `df |> select(!is.na(occupied_beds))`

\needspace{7\baselineskip}
**54R.** Add a column `occupancy_rate`, equal to occupied beds divided by capacity, keeping all the other columns.

(A) `df |> summarise(occupancy_rate = occupied_beds / capacity)`
(B) `df |> mutate(occupancy_rate = occupied_beds / capacity)`
(C) `df$occupancy_rate = occupied_beds / capacity`
(D) `df |> filter(occupied_beds / capacity)`

\needspace{7\baselineskip}
**55R.** Get the total number of occupied beds on each date.

(A) `df |> group_by(date) |> summarise(total = n())`
(B) `df |> group_by(date) |> summarise(total = sum(occupied_beds))`
(C) `df |> group_by(occupied_beds) |> summarise(total = sum(date))`
(D) `df |> summarise(total = sum(occupied_beds))`

\needspace{7\baselineskip}
**56R.** Rename the column `OCCUPANCY_DATE` to `date`.

(A) `df |> rename(OCCUPANCY_DATE = date)`
(B) `df |> select(date)`
(C) `df |> mutate(date = OCCUPANCY_DATE)`
(D) `df |> rename(date = OCCUPANCY_DATE)`

\needspace{7\baselineskip}
**57R.** Make a simulation give the same result every time it is run.

(A) `rnorm(853)`
(B) `seed <- 853`
(C) `set.seed()`
(D) `set.seed(853)`

\needspace{7\baselineskip}
**58R.** Find out how many rows and how many columns the data frame has.

(A) `dim(df)`
(B) `nrow(df)`
(C) `names(df)`
(D) `summary(df)`

\needspace{7\baselineskip}
**59R.** The `date` column was read in as text. Why convert it to a date type (for instance with `as.Date(date)`) before graphing over time?

(A) So the axis is ordered and spaced as time, not as alphabetical labels
(B) It makes no difference to the graph; it is only tidier to store dates as dates
(C) ggplot2 cannot put a text column on an axis at all, and gives an error
(D) Parquet cannot store a text column, so the file could not otherwise be saved

\needspace{7\baselineskip}
**60R.** Save the cleaned data frame, as Parquet, for the paper to read.

(A) `save(df, "cleaned.parquet")`
(B) `write_csv(df, "cleaned.parquet")`
(C) `write_parquet(df, "cleaned.parquet")`
(D) `saveRDS(df, "cleaned.parquet")`

\newpage

# Section C: short answer (ten questions)

A few sentences each. Write in the space provided.

\needspace{6cm}
**S1.** @healy2019 opens with Anscombe's quartet. What do the four datasets have in common, what is different, and what is the lesson for your Donaldson paper?

\vspace{5cm}

\needspace{6cm}
**S2.** Healy separates three ways a figure can be bad. Name them, and give an example of one.

\vspace{5cm}

\needspace{6cm}
**S3.** From the hierarchy of @ClevelandMcGill1984, as Healy presents it: which visual encoding do people judge most accurately, and name one they judge poorly. What does that imply about pie charts?

\vspace{5cm}

\needspace{6cm}
**S4.** @Alexander2023, Chapter 5: list four things a graph needs before it is ready for a reader, and say what to show instead of a boxplot and why.

\vspace{5cm}

\needspace{6cm}
**S5.** Write the chunk options (the `#|` lines) for a chunk that makes a figure which has a caption, can be cross-referenced, and shows no code or warnings in the PDF.

\vspace{5cm}

\needspace{6cm}
**S6.** The Donaldson paper says graphs must show "the actual data, or as close to it as possible". For the dataset you plan to use, describe one graph that does this and one that does not.

\vspace{5cm}

\needspace{6cm}
**S7.** A Donaldson paper that reads its data straight from the Open Data Toronto server when it renders gets 0 overall. Why is that a problem, and what should the workflow be instead?

\vspace{5cm}

\needspace{6cm}
**S8.** Measurement: in two or three sentences, explain how a person spending a night in a Toronto shelter becomes a number in the dataset, and name one way the number could be wrong.

\vspace{5cm}

\needspace{6cm}
**S9.** Name two tests you would write for your cleaned dataset, and say why simulating the data first helps you write them.

\vspace{5cm}

\needspace{6cm}
**S10.** A student's title is "Paper 1: An Analysis of Shelter Data". Give two reasons the rubric would mark this down, and write a better title for a paper on the Week 2 shelter data.

\vspace{5cm}

\newpage

# References
